// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WholesaleApi.Data;

#nullable disable

namespace WholesaleApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429120000_Faz6_DeliveryNotes")]
    partial class Faz6_DeliveryNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Intentionally minimal — full snapshot is in AppDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
